from QPSK_UT import Demodulator_UT, RadioTransmission_UT

Demodulator_UT.shouldDemodulateInputBits()
Demodulator_UT.shouldDemodulateMostOfInputBitsWithNoise()

RadioTransmission_UT.modulateAndDemodulateBits()
